### ISSUE TITLE
Refactor employee

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#255]
# Refactor Request

## Description

Please refactor employee in acourdance with the deliverables below

## Deliverables

- [x] Add employee gives an error when trying to add an employee
- [x] The close button on view employee doesn't work
- [x] In the edit employee add the ability to change superior
- [x] Implement change subordinate
- [x] Implement change supperior
- [x] In the add employee require the role and superior id to be added
- [x] Delete dosn't work
- [x] The colour of text for the phone number and email should be black in light mode and white in dark mode

---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by JessBloem** [comment]
@CodeHermez Plese let me know when you are done making the table functional so that I can check the view, edit and delete functionality.

**Comment by JessBloem** [comment]
The issue has not been completed on time. The due date has been updated to reflect this.

**Comment by JessBloem** [comment]
@CodeHermez This is one of your backlog items

**Comment by JessBloem** [comment]
The issue has not been completed on time. The due date has been updated to reflect this.

**Comment by CodeHermez** [comment]
this issue has been resolved for both giving an employee the superiorID and the role in edit and in add employee 
find screenshots of results attached, take my word the endpoints work now

the issue with the add client giving an error is a backend issue, when I add an employee and I delete them and I add them again that's why it give that issue, something to do with the cascading deletes hamza said...

so for the time being ill leave that one deliverable unchecked but this is done

**Comment by CodeHermez** [comment]
@JessBloem please check my last comment mentioning the issue with the error on adding an employee, I've spoken to hamza about it but I'm afraid he will forget so idk 🤷

**Comment by JessBloem** [comment]
Thank you, I will talk to hamza about it
