### ISSUE TITLE
Calander Update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#327]
# Update Request

## Description

Please update the calander in accordance with the deliverables below

## Deliverables

- [ ] Make the month view have colour around the name of the job 
- [ ] Calendar text colour need to make it visible for both light and dark 
- [ ] Issue with view more event for a month
- [ ] Add a button to show the view of the job

**Comment by JessBloem** [comment]
This issue has not been completed on time. The due dates have been updated

**Comment by JessBloem** [comment]
What is causing you to be stuck?

**Comment by CodeHermez** [comment]
@JessBloem this library is not flexible with any of the things that were listed above and I've been doing research and trying to scrape through the guys who implemented the components stuff and id basically have to reengineer this thing to get even the easiest sounding things on the list, so basically I guess its just one of those things we just have to live with, so I'm keeping this issue here on stuck.

**Comment by JessBloem** [comment]
@CodeHermez we can talk about it in the review meeting
