### ISSUE TITLE
Navbar update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#516]
# Update Request

## Description

Please update the navbar in accordance with the deliverables below

## Deliverables

- [x] Scroll bar. Either close it or more space
- [x] Remove TBD from navbar

**Comment by KumbiraiShonhiwa** [comment]
found out why it appears some places and not others. its because of the main content, if theres not a lot of scrolling required in the main content, the scroll bar on the nav bar will appear. if there is a lot the scroll bar will not appear. 
to test this, go to the meetings page and open all the nav bar items

**Comment by JessBloem** [comment]
This has not been complete. Will be updated
